name: Bot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt

    - name: Lint with flake8 (critical errors)
      run: |
        flake8 --config .flake8 *.py tests/ --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Lint with flake8 (full check)
      run: |
        flake8 --config .flake8 *.py tests/ --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics

    - name: Check code formatting with black
      run: |
        black --check --diff --line-length 100 *.py tests/

    # Isort убран - слишком капризный для внутреннего проекта
    # - name: Check import sorting with isort
    #   run: |
    #     isort --check-only --diff *.py tests/

    - name: Type checking with mypy (informational)
      run: |
        mypy *.py tests/ --ignore-missing-imports
      continue-on-error: true

    - name: Security check with bandit (informational)
      run: |
        bandit -r . -c pyproject.toml
      continue-on-error: true

    - name: Check vulnerabilities with safety
      run: |
        safety check --file requirements.txt
      continue-on-error: true

    - name: Run tests
      run: |
        pytest tests/ -v --tb=short
      env:
        PYTHONPATH: .
